#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\LegacyController' }

controllers:
  resource: ../src/Controller
  type: annotation